import type { Book } from '@/lib/types';

export const books: Book[] = [
  {
    id: 1,
    slug: 'the-whispering-woods',
    title: 'The Whispering Woods',
    author: 'Elara Vance',
    coverImageId: 'book-cover-1',
    description: 'A young botanist discovers a forest that communicates through mesmerizing fungal networks.',
    longDescription: 'In the heart of the mist-shrouded Briarwood, a young botanist named Elara discovers a forest that communicates not with words, but with a complex, mesmerizing fungal network. As she deciphers its ancient secrets, she uncovers a looming threat that could consume the woods and the world beyond.',
    authorBio: 'Elara Vance is a fantasy author with a passion for mycology and ancient forests. Her work explores the delicate connections between humanity and the natural world.',
    genre: 'Fantasy',
    status: 'Published',
    amazonLink: '#',
    ingramLink: '#',
  },
  {
    id: 2,
    slug: 'city-of-echoes',
    title: 'City of Echoes',
    author: 'Kaelen Cross',
    coverImageId: 'book-cover-2',
    description: 'In a neon-drenched metropolis, a detective hunts a phantom who can manipulate memories.',
    longDescription: 'In the rain-slicked, neon-drenched metropolis of Veridia, Detective Kaelen Cross hunts a phantom-like criminal who can steal, alter, and implant memories. To catch a ghost in the machine, Cross must risk his own mind and confront the echoes of his past.',
    authorBio: 'Kaelen Cross writes gritty, philosophical cyberpunk thrillers. A former software engineer, Cross brings a technical authenticity to futuristic noir.',
    genre: 'Sci-Fi',
    status: 'Published',
    amazonLink: '#',
    ingramLink: '#',
  },
  {
    id: 3,
    slug: 'the-last-stargazer',
    title: 'The Last Stargazer',
    author: 'Orion Pax',
    coverImageId: 'book-cover-3',
    description: 'The sole astronomer on a distant outpost must convince a skeptical council of an impending cosmic danger.',
    longDescription: 'As the last astronomer on a lonely deep-space outpost, Dr. Aris Thorne is the sole witness to an impending cosmic catastrophe. He must battle time and a skeptical interplanetary council to save a civilization that has forgotten how to look up at the stars.',
    authorBio: 'Orion Pax is the pseudonym for an astrophysicist and writer who dreams of the stars. "The Last Stargazer" is a love letter to the cosmos and the human spirit of exploration.',
    genre: 'Sci-Fi',
    status: 'Coming Soon',
    amazonLink: '#',
    ingramLink: '#',
  },
  {
    id: 4,
    slug: 'recipes-of-the-forgotten',
    title: 'Recipes of the Forgotten',
    author: 'Sable Blackwood',
    coverImageId: 'book-cover-4',
    description: 'A cursed cookbook passes through generations, its recipes weaving magic and misfortune.',
    longDescription: 'A cursed cookbook, bound in human skin and written in blood, passes through the hands of a cursed family line. Each recipe promises a miracle but exacts a terrible price. From the Dust Bowl to modern-day New Orleans, the book weaves a tapestry of magic, ambition, and misfortune.',
    authorBio: 'Sable Blackwood is a historian specializing in folklore and the occult. Her stories blend meticulous research with a flair for the macabre.',
    genre: 'Horror',
    status: 'Published',
    amazonLink: '#',
    ingramLink: '#',
  },
  {
    id: 5,
    slug: 'the-clockwork-heart',
    title: 'The Clockwork Heart',
    author: 'Augusta Wren',
    coverImageId: 'book-cover-5',
    description: 'An inventor in a steampunk city builds an automaton with a soul, challenging the definition of life.',
    longDescription: 'In the smog-filled, gear-driven city of Aethelburg, a brilliant but disgraced inventor named Alistair builds an automaton with a clockwork heart and a synthetic soul. When his creation, Eva, begins to exhibit genuine emotions, Alistair must protect her from a society that sees her as a threat to both industry and faith.',
    authorBio: 'Augusta Wren is a lover of all things Victorian and an avid tinkerer. "The Clockwork Heart" explores themes of creation, consciousness, and love in a steampunk setting.',
    genre: 'Steampunk',
    status: 'Coming Soon',
    amazonLink: '#',
    ingramLink: '#',
  },
  {
    id: 6,
    slug: 'beneath-the-surface',
    title: 'Beneath the Surface',
    author: 'Marina Salt',
    coverImageId: 'book-cover-6',
    description: 'A marine biologist discovers a sentient deep-sea species just as a corporation plans to strip-mine their habitat.',
    longDescription: 'Dr. Lena Jansen, a marine biologist aboard a deep-sea research vessel, makes a groundbreaking discovery: a sentient, bioluminescent species in the crushing darkness of the Mariana Trench. Her discovery coincides with the arrival of a ruthless corporation intent on strip-mining the trench floor, forcing Lena into a desperate fight to protect a new form of life.',
    authorBio: 'Marina Salt is a deep-sea ecologist and author who uses fiction to explore the wonders and perils of our planet\'s oceans.',
    genre: 'Thriller',
    status: 'Published',
    amazonLink: '#',
    ingramLink: '#',
  },
];
