
import type { Book } from '@/lib/types';

export const books: Book[] = [
  {
    id: 1,
    slug: 'orla-storm-an-interstellar-voyage',
    title: 'Orla Storm: An Interstellar Voyage',
    author: 'W Valentine',
    coverImageId: 'orla-storms-cover',
    description: 'A thrilling adventure that sparks curiosity and celebrates creative thinking.',
    longDescription: 'Orla Storm: An Interstellar Voyage is a heartwarming and imaginative adventure for children aged 7–12. Through vivid illustrations and engaging storytelling, it celebrates the beauty of neurodiversity, the courage to explore, and the power of friendship. Perfect for readers who see the world in unique ways, this story encourages curiosity, creativity, and understanding of different perspectives.\n\nEach chapter is carefully designed to be accessible and enjoyable for neurodivergent and disabled children, while still capturing the wonder and excitement that all young readers crave.\n\nIdeal for libraries, classrooms, and home collections, this book invites children to journey through a universe of discovery, learning, and self-expression. Published by Meddlington Press, it is thoughtfully created to spark imagination and empathy, offering a reading experience that is as inclusive as it is enchanting.',
    authorBio: 'W Valentine lives on the west coast of Ireland and draws inspiration from the landscapes and stories of his home.\n\nAs someone on the spectrum, he brings a unique perspective to his writing, which focuses on neurodivergent experiences to raise awareness among schools, teachers, and the wider public.\n\nHis debut novel, Orla Storm: An Interstellar Voyage, was inspired by becoming a father and a lifelong love of children’s literature.\n\nThrough vivid, technicolour characters, his stories celebrate difference, imagination, and the joy of discovery. He continues to write while building a growing family and hopes to share more adventures in future titles.',
    genre: 'Adventure',
    status: 'Published',
    amazonLink: 'https://www.amazon.com',
    ingramLink: '#',
  },
  {
    id: 2,
    slug: 'finns-wave-of-change',
    title: 'Finn’s Wave of Change',
    author: 'W Valentine',
    coverImageId: 'finns-wave-cover',
    description: 'A heartwarming story about resilience, friendship, and embracing difference.',
    longDescription: 'Join Finn O’Kuti, an eleven-year-old autistic boy from the Dublin suburbs, on a summer adventure that will warm your heart and inspire your spirit!\n\nFeeling like an outsider at school, Finn struggles to fit in—until a two-week surf retreat on the wild Sligo Coast changes everything. With the roar of the Atlantic waves, a shaggy dog named Balthazar waiting at home, and a loving but busy family cheering him on, Finn paddles into uncharted waters.\n\nHe faces towering waves, makes unbreakable friendships, and discovers a confidence he never knew he had. Packed with laughter, triumphs, and heartfelt moments, Finn’s Wave of Change is a story of self-discovery, resilience, and the power of friendship.\n\nPerfect for middle-grade readers aged 7–12, this inclusive and uplifting chapter book celebrates diversity, neurodivergence, and personal growth—and reminds every child that being different is a strength, not a weakness.\n\nRide the wave of friendship. Find your own inner strength.',
    authorBio: 'W Valentine lives on the west coast of Ireland and draws inspiration from the landscapes and stories of his home.\n\nAs someone on the spectrum, he brings a unique perspective to his writing, which focuses on neurodivergent experiences to raise awareness among schools, teachers, and the wider public.\n\nHis debut novel, Orla Storm: An Interstellar Voyage, was inspired by becoming a father and a lifelong love of children’s literature.\n\nThrough vivid, technicolour characters, his stories celebrate difference, imagination, and the joy of discovery. He continues to write while building a growing family and hopes to share more adventures in future titles.',
    genre: 'Picture Book',
    status: 'Coming Soon',
    amazonLink: '#',
    ingramLink: '#',
  },
  {
    id: 3,
    slug: 'the-little-stargazer',
    title: 'The Little Stargazer',
    author: 'Seren Sky',
    coverImageId: 'young-reader-1-cover',
    description: 'A quiet tale of wonder for the youngest dreamers, aged 0-5.',
    longDescription: 'For the youngest readers, this gentle board book follows a little bear who doesn\'t talk much, but sees and feels everything. Follow along as the bear discovers the magic of the night sky, from the quiet glow of the moon to the dance of the fireflies. A perfect bedtime story about finding wonder in stillness.',
    authorBio: 'Seren Sky creates simple, beautiful books for babies and toddlers, focusing on sensory details and emotional connection.',
    genre: 'Board Book',
    status: 'Coming Soon',
    amazonLink: '#',
    ingramLink: '#',
  },
  {
    id: 4,
    slug: 'the-texture-collector',
    title: 'The Texture Collector',
    author: 'Poppy Fields',
    coverImageId: 'young-reader-2-cover',
    description: 'A sensory adventure for little hands and curious minds, aged 0-5.',
    longDescription: 'A little fox loves to collect textures: a smooth, cool pebble; a fuzzy moss patch; a rough piece of bark. This interactive touch-and-feel book invites young children to join in a sensory adventure, exploring the world through touch and celebrating the small details that make it so rich.',
    authorBio: 'Poppy Fields is an early childhood educator who designs books that engage all the senses and encourage hands-on learning.',
    genre: 'Board Book',
    status: 'Coming Soon',
    amazonLink: '#',
    ingramLink: '#',
  },
];
