import type { Book } from '@/lib/types';

export const books: Book[] = [
  {
    id: 1,
    slug: 'orla-storms-an-interstellar-voyage',
    title: 'Orla Storms: An Interstellar Voyage',
    author: 'Leo Archer',
    coverImageId: 'orla-storms-cover',
    description: 'A thrilling adventure that sparks curiosity and celebrates creative thinking.',
    longDescription: 'Join Orla, a girl with a galaxy in her mind, as she builds a spaceship from forgotten treasures and blasts off on an interstellar voyage. Her unique way of seeing the world is her greatest strength, helping her navigate asteroid fields of anxiety and befriend lonely stardust creatures. It\'s a thrilling adventure that sparks curiosity and celebrates the power of a different perspective.',
    authorBio: 'Leo Archer is a storyteller who believes that the most exciting journeys are the ones we take in our minds. He writes books for kids who dream big and think differently.',
    genre: 'Adventure',
    status: 'Published',
    amazonLink: 'https://www.amazon.com',
    ingramLink: '#',
  },
  {
    id: 2,
    slug: 'finns-wave-of-change',
    title: 'Finn’s Wave of Change',
    author: 'Coral Waters',
    coverImageId: 'finns-wave-cover',
    description: 'A heartwarming story about resilience, friendship, and embracing difference.',
    longDescription: 'Finn feels everything as deeply as the ocean. Some days the waves are calm, but other days they crash and roar. This heartwarming story follows Finn as he learns to surf the tides of his emotions with the help of a wise old sea turtle and a friend who understands him. It\'s a tale of resilience, friendship, and the beauty of embracing our own currents.',
    authorBio: 'Coral Waters is a child psychologist and author who lives by the sea. Her stories are inspired by the resilience of children and the calming power of nature.',
    genre: 'Picture Book',
    status: 'Coming Soon',
    amazonLink: '#',
    ingramLink: '#',
  },
  {
    id: 3,
    slug: 'the-little-stargazer',
    title: 'The Little Stargazer',
    author: 'Seren Sky',
    coverImageId: 'young-reader-1-cover',
    description: 'A quiet tale of wonder for the youngest dreamers, aged 0-5.',
    longDescription: 'For the youngest readers, this gentle board book follows a little bear who doesn\'t talk much, but sees and feels everything. Follow along as the bear discovers the magic of the night sky, from the quiet glow of the moon to the dance of the fireflies. A perfect bedtime story about finding wonder in stillness.',
    authorBio: 'Seren Sky creates simple, beautiful books for babies and toddlers, focusing on sensory details and emotional connection.',
    genre: 'Board Book',
    status: 'Coming Soon',
    amazonLink: '#',
    ingramLink: '#',
  },
  {
    id: 4,
    slug: 'the-texture-collector',
    title: 'The Texture Collector',
    author: 'Poppy Fields',
    coverImageId: 'young-reader-2-cover',
    description: 'A sensory adventure for little hands and curious minds, aged 0-5.',
    longDescription: 'A little fox loves to collect textures: a smooth, cool pebble; a fuzzy moss patch; a rough piece of bark. This interactive touch-and-feel book invites young children to join in a sensory adventure, exploring the world through touch and celebrating the small details that make it so rich.',
    authorBio: 'Poppy Fields is an early childhood educator who designs books that engage all the senses and encourage hands-on learning.',
    genre: 'Board Book',
    status: 'Coming Soon',
    amazonLink: '#',
    ingramLink: '#',
  },
];
